Add controllers
SugarFoxy/java-shareit pull request #1
Opened 2022-12-26 16:28 UTC by SugarFoxy

2022-12-27 07:58 UTC, LexLippi requested changes
Привет!

Хорошая работа!
Есть несколько замечаний, которые необходимо исправить!

Желаю удачи!

2022-12-27 07:58 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/exception/handler/ErrorHandler.java
> +    @ResponseStatus(HttpStatus.CONFLICT)
Чаще всего для ошибки валидации используют статус `BadRequest` или `Forbidden`. А `Conflict` используют для сообщения о том, что пользователь пытается добавить уже существующие данные

2022-12-27 07:58 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private Integer id;
А на `id` и `owner` не нужна валидация?

2022-12-27 07:58 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/service/ItemServiceImp.java
> +        userStorage.getUserById(userId);
Зачем этот запрос, если его результат мы игнорируем?
Я так полагаю, что для проверки существования пользователя, но тогда для этого лучше отдельный метод завести, который будет возвращать булево значение - существует пользователь или нет, а то это немного странно выглядит

2022-12-27 07:58 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/storage/ItemStorageImp.java
> +        if (!items.containsKey(id))
Советую в соответствии с Google Code Style всегда использовать скобки, даже когда они опциональны

https://google.github.io/styleguide/javaguide.html#s4.1.1-braces-always-used

2022-12-27 07:58 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/controller/UserController.java
> + */
Если реализовано, надо удалять TODO-шки

2022-12-27 07:58 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/validation/groups/Create.java
> +public interface Create {
Почему классы `Create` и `Update` - пустые?

2022-12-27 07:58 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/storage/UserStorageImp.java
> +    int id = 1;
Модификаторов доступа не хватает

2022-12-27 07:58 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/storage/UserStorageImp.java
> +    private void isExist(String email) {
Может две коллекции `Map` завести, а то долговатый поиск на ровном месте получается

2022-12-27 07:58 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/storage/UserStorageImp.java
> +                doesItExist = true;
Почему сразу исключени не бросить?
К чему эта переменная?

2022-12-29 05:24 UTC, SugarFoxy commented on src/main/java/ru/practicum/shareit/item/dto/ItemDto.java
> +    private Integer id;
Я считаю что не нужна. Id генерируется в хранилище, а owner приходит отдельно от объекта. Когда прилетает объект, в переменных всегда будет null, поэтому нет смысла это проверять.

2022-12-29 06:24 UTC, SugarFoxy commented on src/main/java/ru/practicum/shareit/validation/groups/Create.java
> +public interface Create {
Эти интерфейсы нужны для группировки валидаций в зависимости от запроса. Опиралась на вот этот источник https://habr.com/ru/post/343960/ . Про заполнение интерфейсов там ничего не сказано

2023-01-07 10:23 UTC, merged