Add bookings
SugarFoxy/java-shareit pull request #3
Opened 2023-01-12 17:20 UTC by SugarFoxy

2023-01-13 07:52 UTC, LexLippi requested changes
Привет!

Неплохая работа! 
Но есть несколько замечаний, которые надо исправить!

Желаю удачи!

2023-01-13 07:52 UTC, LexLippi commented on db.shareit.trace.db
> +	at java.base/java.lang.Thread.run(Thread.java:833)
Это зачем?

2023-01-13 07:52 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    private final BookingServiceDb bookingService;
Здесь должен использоваться интерфейс `BookingService`, и в качестве `Qualifier` указываться, что должен использоваться реализация с использованием БД.

Вообще, в идеале сервис не должен знать с чем он работает с БД или с `InMemory` реализацией. Просто с помощью аннотаций подсовывать ему необходимые реализации интерфейсов.

2023-01-13 07:52 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/dto/comparator/BookingComparator.java
> +        }
Можно без `else`, так как выше делаешь `return`, значит туда всегда дойдешь только в том случае, если условие не выполнилось

2023-01-13 07:52 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    Status status;
1. Всегда считаю, что лучше явно прописать модификаторы доступа
2. А здесь вообще можно и приватными эти поля сделать

2023-01-13 07:52 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    LocalDateTime end;
Лучше добавить параметр `nullable = false` в аргументы аннотации `Column`

2023-01-13 07:52 UTC, LexLippi commented on src/main/resources/schema.sql
> +    created TIMESTAMP WITHOUT TIME ZONE,
Точно эти поля могут быть `null`?

2023-01-13 07:52 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/user/storage/UserRepository.java
> +}
Зачем это?

2023-01-13 07:52 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/storage/ItemRepository.java
> +            "where upper(i.name) like upper(concat('%', ?1, '%')) " +
Чтобы регистронезависимо сранивать строки в `PostgreSQL` используют оператор `ilike`

2023-01-14 14:22 UTC, SugarFoxy commented on src/main/java/ru/practicum/shareit/booking/controller/BookingController.java
> +    private final BookingServiceDb bookingService;
Да я знала, спасибо. Это невнимательность на фоне усталости

2023-01-14 14:25 UTC, SugarFoxy commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    Status status;
опять невнимательность

2023-01-14 14:34 UTC, SugarFoxy commented on src/main/java/ru/practicum/shareit/user/storage/UserRepository.java
> +}
это репозиторий  для создания запросных методов. Обошлась стандартными методами, поэтому интерфейс пустой

2023-01-14 14:42 UTC, SugarFoxy commented on src/main/java/ru/practicum/shareit/item/storage/ItemRepository.java
> +            "where upper(i.name) like upper(concat('%', ?1, '%')) " +
В аннотации используется не SQL,  а  JPQL. Запросы на JPQL преобразуются в запросы на диалекте используемой базы данных, а результат запроса преобразуется в экземпляры сущностей или простых Java-классов.   ilike не работает

2023-01-14 14:46 UTC, SugarFoxy commented on db.shareit.trace.db
> +	at java.base/java.lang.Thread.run(Thread.java:833)
Я не знаю что это . Подозреваю что это что то, генерируется идеей при создании бд

2023-01-15 19:23 UTC, LexLippi approved these changes
Привет, хорошая работа!

Оставил пару замечаний, но они из разряда "Можно лучше", так что работу принимаю, можешь исправить их к следующему спринту, если захочешь!

Желаю удачи в дальнейших работах!!!

2023-01-15 19:23 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/booking/dto/comparator/model/Status.java
> +public enum Status {
Лучше явно в названии указывать статусом чего является эта сущность.
В данном случае `BookingStatus`

2023-01-15 19:23 UTC, LexLippi commented on src/main/java/ru/practicum/shareit/item/model/Item.java
> +@Table(name = "items", schema = "public")
Если `schema` - `public`, то ее можно не указывать явно

2023-01-18 21:08 UTC, merged