Add item requests
SugarFoxy/java-shareit pull request #4
Opened 2023-01-25 12:47 UTC by SugarFoxy

2023-01-27 07:24 UTC, LexLippi requested changes
Привет!

Неплохая работа!
Есть некоторые замечания по тестам, которые необходимо поправить!

Желаю удачи!!!

2023-01-27 07:24 UTC, LexLippi commented on src/test/java/ru/practicum/shareit/user/storage/UserRepositoryTest.java
> +    }
Если у тебя 1 тест, то не стоит так заморачиваться.

Более того на самом деле наличие этого пользователя в базе - это логика конкретного теста, а не всего класса в целом

2023-01-27 07:24 UTC, LexLippi commented on src/test/java/ru/practicum/shareit/user/storage/UserRepositoryTest.java
> +public class UserRepositoryTest {
1. В тестовых классах можно опускать все модификаторы доступа, они здесь ни к чему
2. Маловато один тест, честно говоря. Как минимум, можно проверять, что нет ложных срабатываний и пользователь не найдется по несуществующей в базе почте

2023-01-27 07:24 UTC, LexLippi commented on src/test/java/ru/practicum/shareit/user/service/UserServiceDbTest.java
> +        assertEquals(1, usersDto.size());
можно сравнить не только количество элементов, но и содержимое этого списка

2023-01-27 07:24 UTC, LexLippi commented on src/test/java/ru/practicum/shareit/user/service/UserServiceDbTest.java
> +    public void deleteUserById_deletes() {
Лишний модификатор доступа

2023-01-27 07:24 UTC, LexLippi commented on src/test/java/ru/practicum/shareit/item/controller/ItemControllerTest.java
> +    private Item itemUpdateAvailable;
Обычно заводить такое количество полей считается не лучшей идеей. В целом все можно сделать локальными переменными

2023-01-27 07:24 UTC, LexLippi commented on src/test/java/ru/practicum/shareit/booking/dto/BookingOutputDtoTest.java
> +    }
Не вижу принципипальной необходимости в этих методах.
Сильно читаемость кода они не повышают

2023-01-27 10:17 UTC, SugarFoxy commented on src/test/java/ru/practicum/shareit/user/service/UserServiceDbTest.java
> +        assertEquals(1, usersDto.size());
Я торопилась, в других классах так и реализовано. Было желание просто повеситься... Поэтому все приводить в общий вид моральна была не готова. Поправила

2023-01-28 10:33 UTC, LexLippi approved these changes
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!!!

2023-01-31 11:34 UTC, merged