Add docker
SugarFoxy/java-shareit pull request #5
Opened 2023-02-02 19:13 UTC by SugarFoxy

2023-02-03 08:57 UTC, LexLippi requested changes
Привет!

Хорошая работа, оставил некоторое количество комментариев, на некоторые из них можно просто ответить и ничего не переделывать.

Желаю удачи!!!

2023-02-03 08:57 UTC, LexLippi commented on docker-compose.yml
> +      - DB_NAME=shareit
Вообще лучше авторизационные данные для подключения к СУБД не показывать таким образом.
Лучше использовать `env`- файл, который не стоит складывать в репозиторий

https://stackoverflow.com/questions/22651647/docker-and-securing-passwords

2023-02-03 08:57 UTC, LexLippi commented on docker-compose.yml
> +    image: postgres:14.4-alpine
Если интересно, то вышли уже более новые версии:

https://hub.docker.com/_/postgres

Ещё можно использовать такой синтаксис: `postgres:latest`

2023-02-03 08:57 UTC, LexLippi commented on docker-compose.yml
> +      - "5455:5432"
Почему такой маппинг портов?

2023-02-03 08:57 UTC, LexLippi commented on docker-compose.yml
> +      - POSTGRES_PASSWORD=root
Про данные подклчения уже писал

2023-02-03 08:57 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/client/BaseClient.java
> +    private HttpHeaders defaultHeaders(Long userId) {
Мне вот этот метод не очень нравится.
У `GET` и `DELETE` методов нет тела запроса, а мы используем его для всех методов.
Но заголовок `Content-Type` для запросов у которых нет тела - это что-то странное

2023-02-03 08:57 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/client/BaseClient.java
> +        if (response.hasBody()) {
Если у `response` может не быть тела, то странно выглядит заголовок `Accept`, поскольку если ответ на наш запрос не содержит тела, то непонятно для каких данных мы указываем тип.

2023-02-03 08:57 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/client/BaseClient.java
> +    private HttpHeaders defaultHeaders(Long userId) {
Кстати, непонятно почему этот метод не является статическим

2023-02-03 08:57 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/client/BaseClient.java
> +        ResponseEntity<Object> shareitServerResponse;
Я бы не объявлял это до блока `try`, а объявил бы внутри

2023-02-03 08:57 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/client/BaseClient.java
> +        return prepareGatewayResponse(shareitServerResponse);
Этот `return` можно перенести внутрь блока `try`

2023-02-03 08:57 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/client/BaseClient.java
> +                shareitServerResponse = rest.exchange(path, method, requestEntity, Object.class);
Для этого можно использовать тернарный оператор

2023-02-03 08:57 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/client/BaseClient.java
> +        HttpEntity<T> requestEntity = new HttpEntity<>(body, defaultHeaders(userId));
Это кстати тоже можно внутрь `try` запихать

2023-02-03 08:57 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/client/BaseClient.java
> +public class BaseClient {
Это не обязательное к исправлению замечание, а просто наблюдение.
У `RestTemplate` есть специализированные методы для каждого из методов, которые ты используешь `GET, POST, PATCH, DELETE`.

Обычно, если есть более специализированные интерфейсы, то стоит использовать именно их.

2023-02-03 08:57 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/config/RestTemplateConfiguration.java
> +    }
А зачем два бина?
Может их в один объединить?

2023-02-03 08:57 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/exception/handler/ErrorHandler.java
> +        return error;
Зачем сначала инициализировать словарь, потом логгировать запрос, потом возвращать словарь?

Проще было бы логгировать запрос, вернуть словарь, не заводя лишних переменных?
`"error"` можно сделать строковой константой класса

2023-02-03 08:57 UTC, LexLippi commented on server/src/main/resources/application.properties
> +server.port=9090
Не уверен, что такие данные стоит хранить в репозитории. Порт, на котором будет развернут `instance` твоего приложения

2023-02-03 08:57 UTC, LexLippi commented on server/pom.xml
> +        </dependency>
Кажется, эта зависимость больше не нужна

2023-02-03 08:57 UTC, LexLippi commented on gateway/src/main/java/ru/practicum/shareit/user/client/UserClient.java
> +        return get("");
Для таких методов стоит в `BaseClient` сделать конструктор и без этого аргумента

2023-02-03 21:04 UTC, SugarFoxy commented on docker-compose.yml
> +      - DB_NAME=shareit
пришлось оставить их открытыми, иначе вшитые тесты в удаленный репозиторий не пропускают О_о

2023-02-03 21:06 UTC, SugarFoxy commented on docker-compose.yml
> +    image: postgres:14.4-alpine
спасибо, знаю. Но нам сказали работаем с java11 и postgres14

2023-02-03 21:16 UTC, SugarFoxy commented on docker-compose.yml
> +      - "5455:5432"
у меня муж работает в IT, мы делим комп на двоих)))) Можно заметить что коммиты на домашнем компьютере сделаны через его акк. Поэтому внешний порт имеет ближайший свободное значение. а внутренний как то так сложилось, что он у меня ассоциируется с бд, потому что ставится по умолчанию в postgre

2023-02-03 22:00 UTC, SugarFoxy commented on gateway/src/main/java/ru/practicum/shareit/config/RestTemplateConfiguration.java
> +    }
пробовала не получается, для поднятия приложения в тестах Spring ругался на отсутствие бина RestTemplate в базовом клиенте. После добавления начал ругаться на отсутствие бина RestTemplateBuilder в дочерних классах. Не получается объединить это ведь два разных класса или я еще не овладела таким уровнем магии. Если знаешь как их объединить, поделись способом ))

2023-02-04 15:35 UTC, SugarFoxy commented on gateway/src/main/java/ru/practicum/shareit/exception/handler/ErrorHandler.java
> +        return error;
не обращала внимания

2023-02-04 16:00 UTC, SugarFoxy commented on gateway/src/main/java/ru/practicum/shareit/client/BaseClient.java
> +public class BaseClient {
поняла спасибо

2023-02-05 17:13 UTC, SugarFoxy commented
оставила порты в app prop иначе тесты не проходились

2023-02-06 07:57 UTC, LexLippi approved these changes
Привет!

Хорошая работа!

Желаю удачи в следующих спринтах!!!

2024-06-11 16:03 UTC, merged